[mypy]
mypy_path = .
explicit_package_bases = True

warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True
disallow_untyped_defs = True
check_untyped_defs = True

files = a_maze_ing.py, src/