user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr warn;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $body_bytes_sent "$http_referer" "$http_user_agent"';
	access_log /dev/stdout main;

	sendfile on;
	keepalive_timeout 64;
	client_max_body_size 64M;

	server {
		listen 443 ssl;
		server_name __DOMAIN_NAME__;

		root /var/www/html;
		index index.php index.html;

		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_session_cache shared:SSL:10m;
		ssl_session_timeout 10m;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			try_files $uri =404;
			include /etc/nginx/fastcgi_params;
			fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
			fastcgi_param HTTPS on;
			fastcgi_pass wordpress:9000;
		}

		location ~ /\. {
			deny all;
		}
	}
}
